NXP Sabre_iMX6SX_1GB board support added.
ms-iot/u-boot pull request #16
Opened 2019-05-21 18:08 UTC by mvarecha

2019-05-21 18:09 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/ms-iot/u-boot?pullRequest=16) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/ms-iot/u-boot?pullRequest=16) before we can accept your contribution.<br/><br/>:x: mvarecha [sign now](https://cla.opensource.microsoft.com/ms-iot/u-boot?pullRequest=16)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/ms-iot/u-boot?pullRequest=16) it.</sub>

2019-05-21 20:45 UTC, hbeberman requested changes
You should run U-Boot's patch checker tool before making pull requests to catch formatting and style violations. `-c #` specifies how many commits you want to check.
```
./tools/patman/patman.py -n -c 1 -t
```

2019-05-21 20:45 UTC, hbeberman commented on arch/arm/mach-imx/video.c
> +				    displays[i].bus);
U-Boot patch checker: Alignment should match open parenthesis.
```suggestion
					  displays[i].bus);
```

2019-05-21 20:45 UTC, hbeberman commented on arch/arm/mach-imx/video.c
> +					displays[i].pixfmt,
U-Boot patch checker: Alignment should match open parenthesis.

```suggestion
					  displays[i].pixfmt,
```

2019-05-21 20:45 UTC, hbeberman commented on board/freescale/mx6sxsabresd/mx6sxsabresd.c
> +		}
U-Boot style says to not use braces { } for single statement blocks.

2019-05-21 20:45 UTC, hbeberman commented on board/freescale/mx6sxsabresd/mx6sxsabresd.c
> +							ARRAY_SIZE(lvds_ctrl_pads));
U-Boot patch checker: Alignment should match open parenthesis.
```suggestion
					 ARRAY_SIZE(lvds_ctrl_pads));
```

2019-05-21 20:45 UTC, hbeberman commented on board/freescale/mx6sxsabresd/mx6sxsabresd.c
> +	gpio_direction_output(IMX_GPIO_NR(4, 18) , 1);
U-Boot patch checker error: space prohibited before that ','
```suggestion
	gpio_direction_output(IMX_GPIO_NR(4, 18), 1);
```

2019-05-21 20:45 UTC, hbeberman commented on board/freescale/mx6sxsabresd/mx6sxsabresd.c
> +	gpio_direction_output(IMX_GPIO_NR(6, 3) , 1);
U-Boot patch checker error: space prohibited before that ','
```suggestion
	gpio_direction_output(IMX_GPIO_NR(6, 3), 1);
```

2019-05-21 20:45 UTC, hbeberman commented on board/freescale/mx6sxsabresd/mx6sxsabresd.c
> +		.name			= "MCIMX28LCD",
Alignment with the rest of the list.
```suggestion
		.name           = "MCIMX28LCD",
```

2019-05-21 20:45 UTC, hbeberman commented on board/freescale/mx6sxsabresd/mx6sxsabresd.c
> +	if (!(ret)) {
Unnecessary parenthesis. Everywhere else just uses `if (!ret)`
```suggestion
	if (!ret) {
```

2019-05-21 20:45 UTC, hbeberman commented on drivers/video/mxsfb.c
> +	uint32_t base_addr)
U-Boot patch checker: Alignment should match open parenthesis.
```suggestion
			uint32_t base_addr)
```

2019-05-21 20:45 UTC, hbeberman commented on include/configs/mx6sxsabresd.h
> +#define CONFIG_SYS_MALLOC_LEN		(32 * SZ_1M)
This is a pretty big increase over the default. Is it for the framebuffer?

2019-05-23 21:57 UTC, hbeberman approved these changes

2019-05-23 22:05 UTC, christopherco approved these changes

2019-05-24 05:59 UTC, merged